version: '3.9'

services:
  apache:
    image: php:apache
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./website:/var/www/html
      - ./scripts:/var/www/html/scripts
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password  
      MYSQL_DATABASE: counter_db
      MYSQL_USER: counter
      MYSQL_PASSWORD: cntrpassword
    volumes:
      - mysql_data:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpassword

  adminer:
    image: adminer:latest
    ports:
      - "5555:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    depends_on:
        - mysql

  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"

volumes:
  mysql_data: