apiVersion: v1
kind: Service
metadata:
  name: memcached
  namespace: queue-system
spec:
  selector:
    app: memcached
  ports:
    - protocol: TCP
      port: 11211
      targetPort: 11211
  type: ClusterIP
