apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  namespace: queue-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: djpuzo/eq-apache-php-image:v1
        ports:
        - containerPort: 80
        volumeMounts:
        - name: website-volume
          mountPath: /var/www/html
        - name: scripts-volume
          mountPath: /var/www/html/scripts
      volumes:
      - name: website-volume
        hostPath:
          path: /mnt/data/website
          type: Directory
      - name: scripts-volume
        hostPath:
          path: /mnt/data/scripts
          type: Directory
