apiVersion: v1
kind: Service
metadata:
  name: apache
  namespace: queue-system
spec:
  selector:
    app: apache
  ports:
    - protocol: TCP
      port: 80        
      targetPort: 80    
      nodePort: 30080   
  type: NodePort      
